# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6kl9ng4EVfFnUGbOk5--6KF2uN436zU
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Cargar el conjunto de datos de iris
iris = load_iris()
X = iris.data  # Características
y = iris.target  # Etiquetas

# Dividir el conjunto de datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializar y ajustar el modelo KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = knn.predict(X_test)

# Calcular la precisión del modelo
precision = accuracy_score(y_test, y_pred)
print("Precisión del clasificador KNN:", precision)

# Crear una nueva observación (nueva flor de iris)
nueva_flor = [[5.1, 3.5, 1.4, 0.2]]  # Longitud del sépalo, ancho del sépalo, longitud del pétalo, ancho del pétalo

# Utilizar el modelo KNN para predecir la especie de la nueva flor
especie_predicha = knn.predict(nueva_flor)

print("Especie predicha para la nueva flor:", iris.target_names[especie_predicha])